CRITICAL - 2020-06-26 01:40:18 --> Undefined variable: user
#0 C:\xampp\htdocs\warehouse\app\Views\layouts\sidebar.php(18): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(525): CodeIgniter\View\View->render('layouts/sidebar', NULL, true)
#3 C:\xampp\htdocs\warehouse\app\Views\layouts\template.php(24): CodeIgniter\View\View->include('layouts/sidebar')
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(257): CodeIgniter\View\View->render('layouts/templat...', Array, true)
#6 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Common.php(1087): CodeIgniter\View\View->render('dashboard/index', Array, true)
#7 C:\xampp\htdocs\warehouse\app\Controllers\Dashboard.php(7): view('dashboard/index')
#8 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Dashboard->index()
#9 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2020-06-26 02:35:58 --> Undefined property: App\Controllers\Auth::$input
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(16): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 16, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 02:51:05 --> Undefined property: App\Controllers\Auth::$db
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 03:02:56 --> Undefined property: App\Controllers\Auth::$table
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(18): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 03:09:03 --> Class 'App\Model\Users' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:09:23 --> Class 'App\Controllers\Users' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:09:42 --> Class 'App\Model\Users_model' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:10:21 --> Class 'App\Controllers\Users' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:10:56 --> Class 'App\Models\Users_model' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:12:08 --> Class 'App\Models\Users_model' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:13:14 --> Class 'App\Models\Users_model' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:17:37 --> Class 'App\Models\Users_model' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:17:55 --> Class 'App\Controllers\Model\Users_model' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:19:27 --> Class 'App\Models\usersModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:20:02 --> Class 'App\Models\usersModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:21:02 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:01 --> Class 'App\Controllers\App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:16 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:17 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:17 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:17 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:17 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:22:18 --> Class 'App\Models\userModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:23:39 --> Class 'App\Models\UserModel' not found
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2020-06-26 03:33:01 --> Call to undefined method App\Models\UsersModel::get_where
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(34): CodeIgniter\Model->__call('get_where', Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 03:36:25 --> 
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Common.php(813): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(52): redirect('dashboard')
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-06-26 03:37:33 --> 
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Common.php(813): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(52): redirect('dashboard')
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-06-26 03:39:56 --> 
#0 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\HTTP\RedirectResponse.php(92): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('')
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Common.php(813): CodeIgniter\HTTP\RedirectResponse->route(false)
#2 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(65): redirect('auth/login')
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-06-26 03:58:37 --> Undefined variable: data
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 20, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->login()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 04:15:33 --> Undefined property: App\Controllers\Auth::$session
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 04:20:08 --> Undefined property: App\Controllers\Auth::$session
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 04:23:08 --> Undefined property: App\Controllers\Auth::$session
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 04:23:49 --> Undefined variable: session
#0 C:\xampp\htdocs\warehouse\app\Controllers\Auth.php(37): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 37, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Auth->submit()
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-06-26 16:28:11 --> Undefined variable: session
#0 C:\xampp\htdocs\warehouse\app\Views\layouts\sidebar.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(525): CodeIgniter\View\View->render('layouts/sidebar', NULL, true)
#3 C:\xampp\htdocs\warehouse\app\Views\layouts\template.php(24): CodeIgniter\View\View->include('layouts/sidebar')
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(257): CodeIgniter\View\View->render('layouts/templat...', Array, true)
#6 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Common.php(1087): CodeIgniter\View\View->render('dashboard/index', Array, true)
#7 C:\xampp\htdocs\warehouse\app\Controllers\Dashboard.php(7): view('dashboard/index')
#8 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Dashboard->index()
#9 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2020-06-26 16:34:36 --> Undefined variable: session
#0 C:\xampp\htdocs\warehouse\app\Views\layouts\sidebar.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 22, Array)
#1 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(525): CodeIgniter\View\View->render('layouts/sidebar', NULL, true)
#3 C:\xampp\htdocs\warehouse\app\Views\layouts\template.php(25): CodeIgniter\View\View->include('layouts/sidebar')
#4 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\View\View.php(257): CodeIgniter\View\View->render('layouts/templat...', Array, true)
#6 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Common.php(1087): CodeIgniter\View\View->render('dashboard/index', Array, true)
#7 C:\xampp\htdocs\warehouse\app\Controllers\Dashboard.php(7): view('dashboard/index')
#8 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(914): App\Controllers\Dashboard->index()
#9 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
#10 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\warehouse\public\index.php(45): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\warehouse\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#13 {main}
